
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #update update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 42f9415b5670c0ade536a5e387dad012
            client-secret: SvCLJUdQlHQda9JoEjocwBeIkeXCyopw
            scope:
              - profile_nickname
              - profile_image
              - name
              - account_email
              - phone_number
              - age_range
              - gender
              - birthday
              - birthyear
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://117.20.214.163:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id




jwt:
  secret: wow

  expiration:
    access: 900000

    refresh: 3600000